### ISSUE TITLE
Consider using kotlin language to develop v2.0 version.

### ISSUE THREAD

**Issue by lgou2w** [u2g/MoonLake#45]
考虑未来的 `v2.0` 版本将使用 [Kotlin](http://kotlinlang.org/) 语言进行开发.

@xyblues
@Feierr

**Comment by ghost** [comment]
用呗~

**Comment by lgou2w** [comment]
不过 Bukkit 的 Event 设计问题，派生新事件的话只能用 Java 来了

**Comment by lgou2w** [comment]
而且 v2.0 版本的话应该超多内容就会完全重做, 对于一些依赖插件的话不友好 233

**Comment by SimonLover** [comment]
好的 (づ￣ 3￣)づ @lgou2w

**Comment by lgou2w** [comment]
Done. 😄
