### ISSUE TITLE
PaperSpigot server for 1.12.2 is not supported

### ISSUE THREAD

**Issue by anyecraft** [u2g/MoonLake#52]
启用时报错如下:
![5 aq4utgy8sc7q222uc 3ow](https://user-images.githubusercontent.com/32854951/34659774-cd476198-f477-11e7-9837-49dc44e9c86f.png)

玩家加入时报错如下:
![o d1a3 19 t7 z3 r2xjpur](https://user-images.githubusercontent.com/32854951/34659780-e6ef29be-f477-11e7-8d93-e114d08ced8c.png)
且玩家无法加入服务器,卡在登录中

**Comment by lgou2w** [comment]
accepted

**Comment by lgou2w** [comment]
fixed. PaperSpigot no longer uses timings statistics. ty 👍
